In [1]:
import pandas as pd
import sqlite3

In [2]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv"

df = pd.read_csv(url)

conn = sqlite3.connect("spacex.db")

df.to_sql("SPACEXTBL", conn, if_exists="replace", index=False)

90

In [3]:
query = """
SELECT LaunchSite,
COUNT(*) AS TotalLaunches
FROM SPACEXTBL
GROUP BY LaunchSite
"""

pd.read_sql(query, conn)

     LaunchSite  TotalLaunches
0  CCAFS SLC 40             55
1    KSC LC 39A             22
2   VAFB SLC 4E             13

In [4]:
query = """
SELECT Orbit,
COUNT(*) AS Total
FROM SPACEXTBL
GROUP BY Orbit
"""

pd.read_sql(query, conn)

    Orbit  Total
0   ES-L1      1
1     GEO      1
2     GTO     27
3     HEO      1
4     ISS     21
5     LEO      7
6     MEO      3
7      PO      9
8      SO      1
9     SSO      5
10   VLEO     14

In [5]:
query = """
SELECT Outcome,
COUNT(*) AS Total
FROM SPACEXTBL
GROUP BY Outcome
"""

pd.read_sql(query, conn)

       Outcome  Total
0   False ASDS      6
1  False Ocean      2
2   False RTLS      1
3    None ASDS      2
4    None None     19
5    True ASDS     41
6   True Ocean      5
7    True RTLS     14

In [6]:
query = """
SELECT AVG(PayloadMass)
AS AveragePayload
FROM SPACEXTBL
"""

pd.read_sql(query, conn)

   AveragePayload
0     6104.959412